### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by KillSwitch422** [Groestlcoin/Groestlcoin-Easyminer#11]
When installing on new rig, the window does not appear on screen it is active( can bee seen in taskbar), but unless I reconnect display it only shows in the taskbar. This could be since the rig is run without a screen( control is done remotely)

**Comment by Yokomoko** [comment]
How are you connecting to the machine remotely? Remote Desktop? Teamviewer? Logmein? I'll try and replicate and fix.

If it is Windows 10, if you hover over the taskbar icon, and right-click the window that shows above it, and press 'Restore', does it restore OK?

**Comment by KillSwitch422** [comment]
Teamviewer for remote, attached
![screen activate 1](https://user-images.githubusercontent.com/34509332/33940971-be647354-e019-11e7-9147-79fa7da82fbd.PNG)
![screen activate 2](https://user-images.githubusercontent.com/34509332/33940972-be96702a-e019-11e7-8598-c62edc35fd7e.PNG)
![screen activate](https://user-images.githubusercontent.com/34509332/33940973-bec7d05c-e019-11e7-8465-071abce1a7ba.PNG)


 are some screens
the restore is greyed out

**Comment by Yokomoko** [comment]
I believe this to be resolved in 2018 updates.
