### ISSUE TITLE
Format of feedback

### ISSUE THREAD

**Issue by KillSwitch422** [Groestlcoin/Groestlcoin-Easyminer#12]
Just want to know if I have comments/ observations
eg application froze
which logs info do you want attached

Also if I have general comments, regarding GUI updates/discussion ideas should they be listed under Issues?
Should we make a subreddit for the testing when it comes to discussion topics?

**Comment by Yokomoko** [comment]
Logs from the EventViewer are often useful if the application freezes/crashes.

General mining errors - the mining errors for nvidia and CPU can be copied by right-clicking the text window where it logs. AMD can highlight from the command prompt window and press 'Enter'. 

Adding a reddit post for GUI updates/discussions might be the best form, or send me a PM directly here (if that is possible?) or on the Discord channel https://discord.gg/8VURndr

Once the Easyminer is released people can post on the groestlcoin subreddit or add issues here (and then link it from a reddit post if required for further discussion maybe). I think that's the best option.
