### ISSUE TITLE
Virus warning

### ISSUE THREAD

**Issue by KillSwitch422** [Groestlcoin/Groestlcoin-Easyminer#14]
If we want mass adoption, we need to try get away from the antivirus pickups.
These look very suspicious and report as severe. ( I am trusting that there is no malicious stuff in the install)
minerd.exe -> win32/Tigger!rfn
ccminer.exe -> Win32/Tilken.B!cl

I previously used ccminer-x64-2.2.2-cuda9 and had no reports on same rig

**Comment by Yokomoko** [comment]
It'll be difficult to find miners that are consistently not flagged as a virus on every antivirus. I think the best we can do is inform the users that it isn't a virus and explain how to disable / add exceptions. I've done this for windows defender in the wiki. https://github.com/Groestlcoin/Groestlcoin-Easyminer/wiki/How-To-Guide

**Comment by Yokomoko** [comment]
Not possible due to using third party miners, it is out of control even if we recompiled the binaries ourselves.
