### ISSUE TITLE
Nvidia not auto detected

### ISSUE THREAD

**Issue by KillSwitch422** [Groestlcoin/Groestlcoin-Easyminer#15]
Failed to auto detect Nvidia Quattro M2000, ccminer did successfully launch and run after manual include

**Comment by Yokomoko** [comment]
Could you go into start, in the search bar type in dxdiag. And possibly send me a screenshot of what is displayed in 'Display' (Multiples if there are multiple tabs for display). Would be very helpful :)

**Comment by KillSwitch422** [comment]
![nvida](https://user-images.githubusercontent.com/34509332/33940930-96041b62-e019-11e7-81e3-c49a6a249020.PNG)

**Comment by Yokomoko** [comment]
I have made some changes so hopefully it will autodetect on the latest version coming today or tomorrow.
