### ISSUE TITLE
Incorrect spelling in Easyminer disclaimer (GENERAL LEGAL AGREEMENT)

### ISSUE THREAD

**Issue by ghost** [Groestlcoin/Groestlcoin-Easyminer#27]
A legal agreement shouldn't have spelling errors, it damages the reputation of the software.

I don't have time to proofread your disclaimer but some spelling errors I've noticed include:

- "ATEMPT"
- "ADRESS"

Note: Not sure if this is a gramatical error but, you should put a space after and before parenthesis, some are lacking it.

**Comment by Yokomoko** [comment]
Howdy! Where abouts are these spelling errors in the code?

**Comment by ghost** [comment]
Hello! It's in the disclaimer when you first download the software, also it has some in the menu, I can't really pinpoint it to you now, but they are there.
