### ISSUE TITLE
Nvidia mining to SGminer rather than CCminer

### ISSUE THREAD

**Issue by aceoyame** [GroestlCoin/Groestlcoin-Easyminer#4]
Pretty self explanitory,

Need Nvidia hardware to test with. Until then SGminer is being used. This issue is a reminder for tracking so that way it doesn't stay that way.

**Comment by gruve-p** [comment]
Is easyminer not using CCminer now? i think this can be closed now?

**Comment by aceoyame** [comment]
CC mining works in new release
